version: "3.9"

services:
  dovecot:
    image: ajoergensen/dovecot-mailarchive
    volumes:
      - "${MAILDIR_ARCHIVE_DIR?specify maildir archive dir}:/home/app"
    environment:
      MAIL_PASSWORD: "${MAILDIR_BROWSER_DOVECOT_PASSWORD?specify dovecot password}"

  roundcube:
    depends_on:
      - dovecot
    image: roundcube/roundcubemail
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: dovecot
    ports:
      - "9091:80"

